import{S as h,i as u,a as L}from"./assets/vendor-029e731f.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const v="41780713-d9d59fd8c4b13cd5ac9a220da",m=document.querySelector(".gallery"),l=document.querySelector(".load-more-wrapper"),c=document.querySelector(".loader-wrapper"),q=document.querySelector("button.load-more"),b=document.querySelector(".search-form"),f=document.querySelector(".no-more"),w=new h(".gallery li a",{captionsData:"alt",captionDelay:250});let s=[],d=1,y="";const g=40;async function S(){const r=document.querySelector(".search-form input").value;if(!r)return u.error({title:"Error",message:"Please enter a search query"});y!==r?(s=[],d=2,y=r):d+=1,f.classList.remove("is-active"),l.classList.add("is-hidden"),c.classList.add("is-active");try{const o=await L.get("https://pixabay.com/api/",{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:g,page:d}});s.push(...o.data.hits),c.classList.remove("is-active"),l.classList.remove("is-hidden"),o.data.hits.length<g&&(l.classList.add("is-hidden"),f.classList.add("is-active"))}catch{u.error({title:"Error",message:"Something went wrong, try again later!"}),c.classList.remove("is-active")}}async function E(r=!1){const o=s.map(a=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${a.largeImageURL}">
            <img
                class="gallery-image"
                src="${a.webformatURL}"
                alt="${a.tags}"
            />
            </a>
        </li>
        `).join("");if(r?m.innerHTML=o:m.insertAdjacentHTML("beforeend",o),s.length===0)return u.error({title:"Error",message:"No images found for this request"});w.refresh();const i=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}async function p(r=!1){await S(),await E(r)}b.addEventListener("submit",async r=>{r.preventDefault(),p(!0)});q.addEventListener("click",async()=>{p()});
//# sourceMappingURL=commonHelpers.js.map
